# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-17 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classroom',
            name='group_show_open',
            field=models.BooleanField(default=False),
        ),
    ]
