# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-02 11:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0003_auto_20160701_1052'),
    ]

    operations = [
        migrations.AddField(
            model_name='classroom',
            name='event_open',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='classroom',
            name='event_video_open',
            field=models.BooleanField(default=True),
        ),
    ]
