# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 04:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0004_auto_20160702_1927'),
    ]

    operations = [
        migrations.CreateModel(
            name='Note',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('classroo_id', models.IntegerField(default=0)),
                ('lesson', models.CharField(max_length=5)),
                ('memo', models.TextField()),
                ('publication_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.AlterField(
            model_name='classroom',
            name='event_open',
            field=models.BooleanField(default=True),
        ),
    ]
