# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-07-05 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teacher', '0005_auto_20160705_1206'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='note',
            name='classroo_id',
        ),
        migrations.AddField(
            model_name='note',
            name='classroom_id',
            field=models.IntegerField(default=0),
        ),
    ]
