# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-27 00:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_message_messagepoll'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='event_open',
            field=models.BooleanField(default=False),
        ),
    ]
