# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-29 12:27
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_auto_20160629_1837'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='open_time',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 6, 29, 12, 27, 18, 85717, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
