# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-30 04:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_profile_open_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitorlog',
            name='IP',
            field=models.CharField(default='', max_length=20),
            preserve_default=False,
        ),
    ]
