# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-07-02 00:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0011_auto_20160702_0843'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='video_event_open',
            new_name='event_video_open',
        ),
    ]
