# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-20 20:54
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('author_id', models.IntegerField(default=0)),
                ('classroom_id', models.IntegerField(default=0)),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
        migrations.CreateModel(
            name='Debug',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author_id', models.IntegerField(default=0)),
                ('number', models.CharField(max_length=30, unique=True)),
                ('body', models.TextField()),
                ('publish', models.DateTimeField(auto_now_add=True)),
                ('reward', models.IntegerField(default=-1)),
                ('reward_date', models.DateTimeField(auto_now_add=True)),
                ('bug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debugs', to='student.Bug')),
            ],
            options={
                'ordering': ('-publish',),
            },
        ),
    ]
