# -*- coding: utf-8 -*-
# Generated by Django 1.9.2 on 2016-06-29 10:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20160621_0534'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='assistant',
            unique_together=set([('student_id', 'classroom_id', 'lesson')]),
        ),
    ]
